### ISSUE TITLE
Chapter 12

### ISSUE THREAD

**Issue by s1mar** [dougstrouth/CIS228-SQLProgramming#1]
Hello,
can you help me with the Chapter 12 Jail Case Study.I'm literally asking for the answer,I know it's not the right way to learn but I'm in a bit of a tight spot and I'd really appreciate it.Thanks.

**Comment by s1mar** [comment]
Please man,I desperately need help

**Comment by dougstrouth** [comment]
We never covered chapter 12 that I can find. Sorry
